/*
** EPITECH PROJECT, 2024
** B-OOP-400-NCE-4-1-arcade-steven.deffontaine
** File description:
** key
*/

#ifndef KEY_HPP_
    #define KEY_HPP_

        enum e_key {
            UP,
            DOWN,
            LEFT,
            RIGHT,
            SPACE,
            ENTER,
            ESCAPE,
            A,
            B,
            C,
            D,
            E,
            F,
            G,
            H,
            I,
            J,
            K,
            L,
            M,
            N,
            O,
            P,
            Q,
            R,
            S,
            T,
            U,
            V,
            W,
            X,
            Y,
            Z,
            NUM0,
            NUM1,
            NUM2,
            NUM3,
            NUM4,
            NUM5,
            NUM6,
            NUM7,
            NUM8,
            NUM9,
            F1,
            F2,
            F3,
            F4,
            F5,
            F6,
            F7,
            F8,
            F9,
            F10,
            F11,
            F12,
            SHIFT,
            CTRL,
            ALT,
            TAB,
            CAPSLOCK,
            BACKSPACE,
            INSERT,
            HOME,
            PAGEUP,
            DELETE,
            END,
            PAGEDOWN,
            UNKNOWN
        };

#endif /* !KEY_HPP_ */
